const {createClient}=supabase;
const sb=createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);
let session=null,page="home",profile=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
const wa=n=>`https://wa.me/${String(n||"").replace(/\D/g,"")}`;
async function getProfile(){const {data}=await sb.from("profiles").select("*").eq("id",session.user.id).maybeSingle();profile=data||{id:session.user.id,name:session.user.email,role:"parent"}}
function loginView(){return `<div class="login"><div class="login-card"><div class="logo">VX7X</div><h1>Studio Management</h1><p class="muted">Admin • Trainer • Parent</p><form onsubmit="login(event)"><div class="field"><label>Email</label><input id="email" type="email" required></div><div class="field"><label>Password</label><input id="password" type="password" required></div><button class="btn" style="width:100%">Login</button></form><div class="demo">New users are created by the Admin. Demo accounts from the old local version are not cloud accounts.</div></div></div>`}
const menus=()=>profile?.role==="admin"?[["home","Dashboard"],["students","Students"],["batches","Batches"],["attendance","Attendance"],["fees","Fees"],["updates","Updates"],["reports","Reports"],["settings","Settings"]]:profile?.role==="trainer"?[["home","Dashboard"],["batches","My Batches"],["attendance","Attendance"],["updates","Updates"]]:[["home","Home"],["attendance","Attendance"],["fees","Fees"],["updates","Updates"],["profile","Profile"]];
async function shell(){return `<div class="top"><b>VX7X DANCE & FITNESS</b><div>${esc(profile?.name||"")} · <button class="btn secondary" onclick="logout()">Logout</button></div></div><div class="layout"><aside class="side">${menus().map(m=>`<button class="${page===m[0]?"active":""}" onclick="go('${m[0]}')">${m[1]}</button>`).join("")}</aside><main class="main">${await renderPage()}</main></div><nav class="bottom">${menus().slice(0,5).map(m=>`<button onclick="go('${m[0]}')">${m[1]}</button>`).join("")}</nav>`}
async function home(){if(profile.role==="admin"){const [{count:students},{count:batches},{count:trainers},{data:payments}]=await Promise.all([sb.from("students").select("*",{count:"exact",head:true}),sb.from("batches").select("*",{count:"exact",head:true}),sb.from("profiles").select("*",{count:"exact",head:true}).eq("role","trainer"),sb.from("payments").select("amount,status")]);const paid=(payments||[]).filter(p=>p.status==="paid").reduce((a,p)=>a+Number(p.amount),0);return `<div class="grid"><div class="card">Students<div class="stat">${students||0}</div></div><div class="card">Trainers<div class="stat">${trainers||0}</div></div><div class="card">Batches<div class="stat">${batches||0}</div></div><div class="card">Collected<div class="stat">${money(paid)}</div></div></div><br><div class="card"><h2>Quick Actions</h2><div class="actions"><button class="btn" onclick="go('students')">+ Add Student</button><button class="btn" onclick="go('attendance')">✓ Attendance</button><button class="btn" onclick="go('fees')">₹ Fees</button><button class="btn" onclick="go('updates')">📢 Update</button></div></div>`}
if(profile.role==="trainer"){const {data}=await sb.from("batches").select("id,name,style,days,start_time,end_time").eq("trainer_id",profile.id);return `<h1>Welcome, ${esc(profile.name)}</h1><div class="grid">${(data||[]).map(b=>`<div class="card"><h2>${esc(b.name)}</h2><p>${esc(b.style||"")}<br>${esc(b.days||"")}<br>${esc(b.start_time||"")} - ${esc(b.end_time||"")}</p><button class="btn" onclick="go('attendance')">Mark Attendance</button></div>`).join("")}</div>`}
const {data:children}=await sb.from("students").select("*,batches(name,start_time,end_time)").eq("parent_id",profile.id);return `<h1>Welcome, ${esc(profile.name)}</h1>${(children||[]).map(s=>`<div class="card"><h2>${esc(s.name)}</h2><p>${esc(s.batches?.name||"")}</p><div class="actions"><button class="btn" onclick="go('fees')">Pay Fees</button><button class="btn secondary" onclick="go('attendance')">Attendance</button></div></div>`).join("")||"<div class='card'>No students linked to this parent yet.</div>"}`}
async function studentsPage(){const {data}=await sb.from("students").select("*,batches(name)").order("name");return `<div class="section-title"><h1>Students</h1><button class="btn" onclick="studentForm()">+ Add Student</button></div><div class="table-wrap"><table class="table"><tr><th>Name</th><th>Parent</th><th>Batch</th><th>Phone</th><th>Status</th></tr>${(data||[]).map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.parent_name||"")}</td><td>${esc(s.batches?.name||"")}</td><td><a href="${wa(s.phone)}" target="_blank">${esc(s.phone||"")}</a></td><td><span class="pill green">${esc(s.status||"active")}</span></td></tr>`).join("")}</table></div>`}
function studentForm(){const modal=document.createElement("div");modal.id="modal";modal.innerHTML=`<div class="login" style="position:fixed;inset:0;background:#0008;z-index:20"><div class="login-card"><h2>Add Student</h2><form onsubmit="saveStudent(event)"><div class="field"><label>Student Name</label><input id="sn" required></div><div class="field"><label>Parent Name</label><input id="pn" required></div><div class="field"><label>Parent Email</label><input id="pe" type="email"></div><div class="field"><label>Phone/WhatsApp</label><input id="ph"></div><div class="field"><label>Batch</label><select id="bi"></select></div><div class="actions"><button class="btn">Save</button><button type="button" class="btn secondary" onclick="modal.remove()">Cancel</button></div></form></div></div>`;document.body.appendChild(modal);sb.from("batches").select("id,name").then(({data})=>{bi.innerHTML=(data||[]).map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join("")})}
async function saveStudent(e){e.preventDefault();const {error}=await sb.from("students").insert({name:sn.value,parent_name:pn.value,parent_email:pe.value||null,phone:ph.value||null,batch_id:bi.value,status:"active"});if(error)alert(error.message);else{modal.remove();render()}}
async function batchesPage(){const {data}=await sb.from("batches").select("*,profiles!batches_trainer_id_fkey(name)").order("name");return `<div class="section-title"><h1>${profile.role==="trainer"?"My Batches":"Batches"}</h1></div><div class="grid">${(data||[]).map(b=>`<div class="card"><h2>${esc(b.name)}</h2><p>${esc(b.style||"")}<br>${esc(b.days||"")}<br>${esc(b.start_time||"")} - ${esc(b.end_time||"")}</p><p>Fee: <b>${money(b.monthly_fee)}</b></p></div>`).join("")}</div>`}
async function attendancePage(){let q=sb.from("students").select("id,name,batch_id,batches(name)");if(profile.role==="parent")q=q.eq("parent_id",profile.id);const {data}=await q.order("name");return `<h1>Attendance</h1><div class="table-wrap"><table class="table"><tr><th>Student</th><th>Batch</th><th>Action</th></tr>${(data||[]).map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.batches?.name||"")}</td><td>${profile.role==="parent"?"View attendance":`<button class="btn success" onclick="mark('${s.id}','present')">Present</button> <button class="btn danger" onclick="mark('${s.id}','absent')">Absent</button>`}</td></tr>`).join("")}</table></div>`}
async function mark(studentId,status){const date=new Date().toISOString().slice(0,10);const {error}=await sb.from("attendance").upsert({student_id:studentId,date,status,marked_by:profile.id},{onConflict:"student_id,date"});if(error)alert(error.message);else alert("Attendance saved");}
async function feesPage(){let q=sb.from("students").select("id,name,batch_id,batches(name,monthly_fee)").order("name");if(profile.role==="parent")q=q.eq("parent_id",profile.id);const {data}=await q;return `<h1>Fees</h1>${(data||[]).map(s=>`<div class="card"><h2>${esc(s.name)}</h2><p>${esc(s.batches?.name||"")}</p><div class="stat">${money(s.batches?.monthly_fee)} / month</div><br><div class="actions">${profile.role==="parent"?`<button class="btn" onclick="pay('${s.id}','${s.batches?.monthly_fee||0}')">Pay Fees</button>`:`<button class="btn success" onclick="record('${s.id}','${s.batches?.monthly_fee||0}')">Record Payment</button>`}</div></div>`).join("")}`}
function pay(id,amount){alert("Connect your UPI ID/QR in Admin Settings, then parents can pay here.")}
async function record(id,amount){const ref=prompt("Enter transaction/reference number");if(ref===null)return;const {error}=await sb.from("payments").insert({student_id:id,amount:Number(amount),status:"paid",payment_date:new Date().toISOString().slice(0,10),reference:ref});if(error)alert(error.message);else{alert("Payment recorded");render()}}
async function updatesPage(){const {data}=await sb.from("announcements").select("*").order("created_at",{ascending:false});return `<div class="section-title"><h1>Studio Updates</h1>${profile.role==="admin"?`<button class="btn" onclick="updateForm()">+ Post Update</button>`:""}</div>${(data||[]).map(x=>`<div class="notice"><b>${esc(x.title)}</b><br>${esc(x.body)}<br><small>${new Date(x.created_at).toLocaleDateString()}</small></div>`).join("")||"<div class='card'>No updates.</div>"}`}
function updateForm(){const modal=document.createElement("div");modal.id="modal";modal.innerHTML=`<div class="login" style="position:fixed;inset:0;background:#0008;z-index:20"><div class="login-card"><h2>Post Update</h2><form onsubmit="saveUpdate(event)"><div class="field"><label>Title</label><input id="ut" required></div><div class="field"><label>Message</label><textarea id="ub" required></textarea></div><button class="btn">Publish</button></form></div></div>`;document.body.appendChild(modal)}
async function saveUpdate(e){e.preventDefault();const {error}=await sb.from("announcements").insert({title:ut.value,body:ub.value,created_by:profile.id});if(error)alert(error.message);else{modal.remove();render()}}
async function reportsPage(){const {data}=await sb.from("payments").select("*,students(name)").order("payment_date",{ascending:false});return `<h1>Reports</h1><div class="card"><div class="table-wrap"><table class="table"><tr><th>Date</th><th>Student</th><th>Amount</th><th>Status</th><th>Reference</th></tr>${(data||[]).map(p=>`<tr><td>${p.payment_date}</td><td>${esc(p.students?.name||"")}</td><td>${money(p.amount)}</td><td>${esc(p.status)}</td><td>${esc(p.reference||"")}</td></tr>`).join("")}</table></div></div>`}
function settingsPage(){return `<h1>Settings</h1><div class="card"><p>Supabase is connected. Payment QR/UPI settings will be added after the database is initialized.</p><p class="muted">Keep secret/service-role keys out of this browser app.</p></div>`}
async function renderPage(){switch(page){case"students":return studentsPage();case"batches":return batchesPage();case"attendance":return attendancePage();case"fees":return feesPage();case"updates":return updatesPage();case"reports":return reportsPage();case"settings":return settingsPage();case"profile":return `<h1>Profile</h1><div class="card"><h2>${esc(profile.name)}</h2><p>Role: ${esc(profile.role)}</p></div>`;default:return home()}}
async function render(){if(!session){app.innerHTML=loginView();return}app.innerHTML=await shell()}
async function login(e){e.preventDefault();const {data,error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});if(error){alert(error.message);return}session=data.session;await getProfile();page="home";render()}
async function logout(){await sb.auth.signOut();session=null;profile=null;render()}
async function go(p){page=p;render()}
sb.auth.getSession().then(async ({data})=>{session=data.session;if(session){await getProfile()}render()});
